# Authentik outputs
output "authentik_application_id" {
  description = "Authentik application ID"
  value       = var.create_authentik_app ? authentik_application.this[0].id : null
}

output "authentik_application_uuid" {
  description = "Authentik application UUID (for policy bindings)"
  value       = var.create_authentik_app ? authentik_application.this[0].uuid : null
}

output "proxy_provider_id" {
  description = "Proxy provider ID (for outpost configuration)"
  value       = var.auth_mode == "forward_auth" && var.create_authentik_app ? authentik_provider_proxy.this[0].id : null
}

output "ldap_provider_id" {
  description = "LDAP provider ID (for outpost configuration)"
  value       = var.auth_mode == "ldap" && var.create_authentik_app ? authentik_provider_ldap.this[0].id : null
}

output "oauth_client_id" {
  description = "OAuth2 client ID"
  value       = var.auth_mode == "oauth" && var.create_authentik_app ? authentik_provider_oauth2.this[0].client_id : null
}

output "oauth_client_secret" {
  description = "OAuth2 client secret (generated by Authentik)"
  value       = var.auth_mode == "oauth" && var.create_authentik_app ? authentik_provider_oauth2.this[0].client_secret : null
  sensitive   = true
}

# LDAP connection details
output "ldap_base_dn" {
  description = "LDAP base DN"
  value       = var.auth_mode == "ldap" ? var.ldap_base_dn : null
}

# Homarr outputs
output "homarr_app_id" {
  description = "Homarr app tile ID"
  value       = var.create_homarr_tile ? homarr_app.this[0].id : null
}

output "homarr_integration_id" {
  description = "Homarr integration ID"
  value       = length(homarr_integration.this) > 0 ? homarr_integration.this[0].id : null
}
